version: "3.9"

services:
  admin-module:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: admin-module
    environment:
      - ADMIN_POSTGRES_HOST=db
      - ADMIN_POSTGRES_PORT=5432
      - ADMIN_POSTGRES_DB=admin_db
      - ADMIN_POSTGRES_USER=admin
      - ADMIN_POSTGRES_PASSWORD=admin
      - ADMIN_SECRET_KEY=CHANGE_ME_SUPER_SECRET
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - admin-net

  db:
    image: postgres:15-alpine
    container_name: admin-postgres
    environment:
      - POSTGRES_DB=admin_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # локально, чтобы не конфликтовать
    restart: unless-stopped
    networks:
      - admin-net

networks:
  admin-net:
    driver: bridge

volumes:
  postgres_data:
