[project]
name = "admin-module"
version = "0.1.0"
authors = [
    { name = "Egor", email = "dontmover@duck.com" }
]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
